spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/miniautorizador
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
  output:
    ansi:
      enabled: ALWAYS