spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miniautorizador
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
  output:
    ansi:
      enabled: ALWAYS